repos:
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.2.0
  hooks:
  - id: black
    language_version: python3.10
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.7.0
  hooks:
  -   id: reorder-python-imports
- repo: https://github.com/PyCQA/autoflake
  rev: v2.2.1
  hooks:
  -   id: autoflake
      args: [--remove-all-unused-imports, --remove-unused-variables, --in-place]
- repo: https://github.com/pycqa/flake8
  rev: '3.7.7'
  hooks:
  - id: flake8
    language_version: python3
#- repo: git://github.com/skorokithakis/pre-commit-mypy
#  rev: v0.610
#  hooks:
#  - id: mypy
#    args: [-s]
#- repo: local
#  hooks:
#  - id: gitchangelog
#    language: system
#    always_run: true
#    pass_filenames: false
#    name: Generate changelog
#    entry: bash -c "gitchangelog > CHANGELOG.md"
#    stages: [commit]
